### ISSUE TITLE
 运行34b模型时torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by jarod-jin** [01-ai/Yi#125]
[2023-11-14 09:43:19,352] [INFO] [config.py:972:print]   zero_enabled ................. True
[2023-11-14 09:43:19,352] [INFO] [config.py:972:print]   zero_force_ds_cpu_optimizer .. True
[2023-11-14 09:43:19,352] [INFO] [config.py:972:print]   zero_optimization_stage ...... 2
[2023-11-14 09:43:19,352] [INFO] [config.py:958:print_user_config]   json = {
    "train_batch_size": 4, 
    "train_micro_batch_size_per_gpu": 1, 
    "steps_per_print": 10, 
    "zero_optimization": {
        "stage": 2, 
        "offload_param": {
            "device": "cpu"
        }, 
        "offload_optimizer": {
            "device": "cpu"
        }, 
        "stage3_param_persistence_threshold": 1.000000e+04, 
        "stage3_max_live_parameters": 3.000000e+07, 
        "stage3_prefetch_bucket_size": 3.000000e+07, 
        "memory_efficient_linear": false
    }, 
    "fp16": {
        "enabled": true, 
        "loss_scale_window": 100
    }, 
    "gradient_clipping": 1.0, 
    "prescale_gradients": false, 
    "wall_clock_breakdown": false, 
    "hybrid_engine": {
        "enabled": false, 
        "max_out_tokens": 512, 
        "inference_tp_size": 1, 
        "release_inference_cache": false, 
        "pin_parameters": true, 
        "tp_gather_partition_size": 8
    }, 
    "tensorboard": {
        "enabled": false, 
        "output_path": "sft_tensorboard/ds_tensorboard_logs/", 
        "job_name": "sft_tensorboard"
    }
}
***** Running training *****
***** Evaluating perplexity, Epoch 0/4 *****
Traceback (most recent call last):
  File "/opt/yi/finetune/sft/main.py", line 408, in <module>
    main()
  File "/opt/yi/finetune/sft/main.py", line 361, in main
    perplexity = evaluation(model, eval_dataloader)
  File "/opt/yi/finetune/sft/main.py", line 308, in evaluation
    outputs = model(**batch)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1807, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 818, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 372, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 305, in forward
    ).to(query_states.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.75 GiB (GPU 0; 79.35 GiB total capacity; 76.19 GiB already allocated; 998.19 MiB free; 76.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/opt/yi/finetune/sft/main.py", line 408, in <module>
    main()
  File "/opt/yi/finetune/sft/main.py", line 361, in main
    perplexity = evaluation(model, eval_dataloader)
  File "/opt/yi/finetune/sft/main.py", line 308, in evaluation
    outputs = model(**batch)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1807, in forward
    loss = self.module(*inputs, **kwargs)
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 818, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 372, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/envs/dev_env_yi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_yi.py", line 305, in forward
    ).to(query_states.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.75 GiB (GPU 1; 79.35 GiB total capacity; 76.19 GiB already allocated; 806.19 MiB free; 76.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by jarod-jin** [comment]
使用8卡A800 1.8T内存的训练机

**Comment by jiangchengSilent** [comment]
> 使用8卡A800 1.8T内存的训练机

这个硬件配置内存充足，可以考虑增大单节点中的并发量，例如将finetune/scripts/run_sft_Yi_34b.sh里的CUDA_VISIBLE_DEVICES设成0,1,2,3,4,5,6,7
通过并发量的增加，结合zero2，看看显存是否能跑

**Comment by jarod-jin** [comment]
我开始就是使用8块卡结果直接oom 然后换4块一样oom

**Comment by jiangchengSilent** [comment]
> 我开始就是使用8块卡结果直接oom 然后换4块一样oom

麻烦提供一下启动脚本，谢谢

**Comment by jarod-jin** [comment]
#/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")/../sft/"

export CUDA_VISIBLE_DEVICES=0,1,2,3 #limit parallelism to avoid cpu oom

deepspeed main.py \
	--data_path /opt/data_set/yowant_yi_dataset \
	--model_name_or_path /opt/ai_models/Yi-34B-200K/ \
	--per_device_train_batch_size 1 \
	--per_device_eval_batch_size 1 \
	--max_seq_len 4096 \
	--learning_rate 2e-6 \
	--weight_decay 0. \
	--num_train_epochs 4 \
	--training_debug_steps 50 \
	--gradient_accumulation_steps 1 \
	--lr_scheduler_type cosine \
	--num_warmup_steps 0 \
	--seed 1234 \
	--gradient_checkpointing \
	--zero_stage 2 \
	--deepspeed \
	--offload \
	--output_dir /opt/ai_models/finetune \

**Comment by jiangchengSilent** [comment]
200k模型在单节点上确实会OOM，因为config.json里边的max_position_embedding都是200k，会消耗更大的显存。默认的script针对的是基础的Yi-34B， max_position_embedding是4096
针对200k模型，建议考虑deepspeed -H hostfile main.py ..这样的形式进行多节点的训练，可能需要64卡左右

**Comment by jarod-jin** [comment]
好吧

**Comment by chenyzh28** [comment]
> 200k模型在单节点上确实会OOM，因为config.json里边的max_position_embedding都是200k，会消耗更大的显存。默认的script针对的是基础的Yi-34B， max_position_embedding是4096 针对200k模型，建议考虑deepspeed -H hostfile main.py ..这样的形式进行多节点的训练

为什么我训练基础的Yi-34B的时候，模型加载的时候就直接爆内存然后被kill了呢。配置和上面的差不多，8卡A800 900G内存。

**Comment by jiangchengSilent** [comment]
> 为什么我训练基础的Yi-34B的时候，模型加载的时候就直接爆内存然后被kill了呢。配置和上面的差不多，8卡A800 900G内存。

采用zero2+offload的时候deepspeed.initialize这一步非常消耗内存，因此需要限制子进程的数量，例如通过CUDA_VISIBLE_DEVICES=0,1,2,3来限制子进程为4，因为子进程为6或者8的时候容易爆

**Comment by chenyzh28** [comment]
> > 为什么我训练基础的Yi-34B的时候，模型加载的时候就直接爆内存然后被kill了呢。配置和上面的差不多，8卡A800 900G内存。
> 
> 采用zero2+offload的时候deepspeed.initialize这一步非常消耗内存，因此需要限制子进程的数量，例如通过CUDA_VISIBLE_DEVICES=0,1,2,3来限制子进程为4，因为子进程为6或者8的时候容易爆
> 
> 你可以在运行的时候，另外开一个窗口，用top -c然后看看RES那一列的内存消耗情况

我在持续观测内存占用，确实是爆了之后开始报错的。只使用4卡的话，显存够用吗？

**Comment by jiangchengSilent** [comment]
> > > 为什么我训练基础的Yi-34B的时候，模型加载的时候就直接爆内存然后被kill了呢。配置和上面的差不多，8卡A800 900G内存。
> > 
> > 
> > 采用zero2+offload的时候deepspeed.initialize这一步非常消耗内存，因此需要限制子进程的数量，例如通过CUDA_VISIBLE_DEVICES=0,1,2,3来限制子进程为4，因为子进程为6或者8的时候容易爆
> > 你可以在运行的时候，另外开一个窗口，用top -c然后看看RES那一列的内存消耗情况
> 
> 我在持续观测内存占用，确实是爆了之后开始报错的。只使用4卡的话，显存够用吗？

4k长度是够的，但比较borderline了，如果要进一步改需要用multi-node，或者换zero3了

**Comment by chenyzh28** [comment]
> > > > 为什么我训练基础的Yi-34B的时候，模型加载的时候就直接爆内存然后被kill了呢。配置和上面的差不多，8卡A800 900G内存。
> > > 
> > > 
> > > 采用zero2+offload的时候deepspeed.initialize这一步非常消耗内存，因此需要限制子进程的数量，例如通过CUDA_VISIBLE_DEVICES=0,1,2,3来限制子进程为4，因为子进程为6或者8的时候容易爆
> > > 你可以在运行的时候，另外开一个窗口，用top -c然后看看RES那一列的内存消耗情况
> > 
> > 
> > 我在持续观测内存占用，确实是爆了之后开始报错的。只使用4卡的话，显存够用吗？
> 
> 4k长度是够的，但比较borderline了，如果要进一步改需要用multi-node，或者换zero3了

好的，我试试，请教一下，这里的offload是为了降低显存占用牺牲内存吗？之前finetune其他模型的时候好像没有用到这个。
