### ISSUE TITLE
ValueError: Trying to set a tensor of shape torch.Size([0]) in "weight" (which has shape torch.Size([64000, 7168])), this look incorrect.

### ISSUE THREAD

**Issue by lifengyu2005** [01-ai/Yi#129]
Traceback (most recent call last):
  File "/root/lifengyu/Yi/Yi/finetune/sft/prompt_eval.py", line 179, in <module>
    main()
  File "/root/lifengyu/Yi/Yi/finetune/sft/prompt_eval.py", line 156, in main
    model_fintuned = create_hf_model(
  File "/root/lifengyu/Yi/Yi/finetune/utils/model/model_utils.py", line 37, in create_hf_model
    model = model_class.from_pretrained(
  File "/root/anaconda3/envs/yienv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/yienv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3307, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/anaconda3/envs/yienv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3695, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/root/anaconda3/envs/yienv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 741, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/root/anaconda3/envs/yienv/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([0]) in "weight" (which has shape torch.Size([64000, 7168])), this look incorrect.

run_eval.sh 测试run_sft_Yi_34b.sh训练后的模型，在加载finetuned_model模型时报错，训练过程中没有报错
请问什么原因？

**Comment by jiangchengSilent** [comment]
你好，麻烦在finetuned模型路径下ll -ah把文件大小信息打印粘贴一下，以及运行run_sft_Yi_34b.sh是否修改过原始脚本中的参数？

**Comment by caoxu915683474** [comment]
你好，我也遇到了这个问题，这个后面怎么解决的呀？

**Comment by jiangchengSilent** [comment]
> 你好，我也遇到了这个问题，这个后面怎么解决的呀？

你好，请看一下你的输出模型文件路径里的pytorch_model.bin文件的大小，如果在65G左右是正常的，否则是模型save阶段异常

**Comment by caoxu915683474** [comment]
好的
