### ISSUE TITLE
ImportError: DLL load failed while importing awq_inference_engine: 找不到指定的模块。

### ISSUE THREAD

**Issue by seedclaimer** [01-ai/Yi#214]
seem to be awq install problem on windows

 Traceback (most recent call last):
  File "E:\Projects_Python\CY_PYQ\use.py", line 9, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python311\Lib\site-packages\transformers\modeling_utils.py", line 3319, in from_pretrained
    model, has_been_replaced = replace_with_awq_linear(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python311\Lib\site-packages\transformers\integrations\awq.py", line 62, in replace_with_awq_linear
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "E:\python311\Lib\site-packages\awq\__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "E:\python311\Lib\site-packages\awq\models\__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "E:\python311\Lib\site-packages\awq\models\mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "E:\python311\Lib\site-packages\awq\models\base.py", line 12, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "E:\python311\Lib\site-packages\awq\quantize\quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "E:\python311\Lib\site-packages\awq\modules\linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by findmyway** [comment]
可以在 AWQ 的 repo 下咨询
