### ISSUE TITLE
base_model如何下载？

### ISSUE THREAD

**Issue by dhcn** [01-ai/Yi#215]
Traceback (most recent call last):
  File "main.py", line 413, in <module>
    main()
  File "main.py", line 250, in main
    tokenizer = load_hf_tokenizer(args.model_name_or_path, fast_tokenizer=False)
  File "/mnt/workspace/Yi/finetune/sft/utils/utils.py", line 64, in load_hf_tokenizer
    tokenizer = get_tokenizer(model_name_or_path, fast_tokenizer=fast_tokenizer)
  File "/mnt/workspace/Yi/finetune/sft/utils/utils.py", line 43, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 701, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 534, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '/base_model'.
[2023-11-30 10:36:20,067] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 591
[2023-11-30 10:36:20,068] [ERROR] [launch.py:321:sigkill_handler] ['/opt/conda/bin/python', '-u', 'main.py', '--local_rank=0', '--data_path', '../yi_example_dataset/', '--model_name_or_path', '/base_model', '--per_device_train_batch_size', '1', '--per_device_eval_batch_size', '1', '--max_seq_len', '4096', '--learning_rate', '2e-6', '--weight_decay', '0.', '--num_train_epochs', '4', '--training_debug_steps', '20', '--gradient_accumulation_steps', '1', '--lr_scheduler_type', 'cosine', '--num_warmup_steps', '0', '--seed', '1234', '--gradient_checkpointing', '--zero_stage', '2', '--deepspeed', '--offload', '--output_dir', './finetuned_model'] exits with return code = 1

**Comment by findmyway** [comment]
实例代码里，假设模型已经放在了 `/base_model` 目录下，你需要先手动从 HuggingFace, ModelScope, WiseModel等处先下载模型，然后在运行时指定具体的路径。

具体下载链接参考 README 中的内容。
