### ISSUE TITLE
ValueError: weight is on the meta device, we need a `value` to put in on 0.

### ISSUE THREAD

**Issue by xieeryihe** [01-ai/Yi#225]
我用的离线模型34B-chat，运行各种官方demo的时候，都会发生发生如下错误
> ValueError: weight is on the meta device, we need a `value` to put in on 0.

Traceback如下：

Traceback (most recent call last):
  File "/root/autodl-tmp/x.py", line 78, in <module>
    main(args)
  File "/root/autodl-tmp/x.py", line 49, in main
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3539, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/big_modeling.py", line 396, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/hooks.py", line 537, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/hooks.py", line 537, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/hooks.py", line 507, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/hooks.py", line 253, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/root/miniconda3/envs/yi/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 281, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
ValueError: weight is on the meta device, we need a `value` to put in on 0.

请问这是为什么

**Comment by xieeryihe** [comment]
pytorch：2.1.1
cuda：12.1

**Comment by findmyway** [comment]
但从上面的信息看，似乎是上游 accelerate 的原因，可以在那边进一步咨询下
Ref: https://github.com/huggingface/accelerate/issues/1289

**Comment by findmyway** [comment]
> 模型使用的是pytorch_model-00001-of-00007.bin那一系列

这个具体是指？
Chat 模型现在都是 safetensors 的格式，不确定你是指的哪个模型
？

**Comment by xieeryihe** [comment]
![image](https://github.com/01-ai/Yi/assets/58676324/cf65c6dd-85cc-4328-9ccf-f36d32ee1fd9)
不是有两个版本吗，safetensors和pytorch。
这个 hf 上的 [discussions](https://huggingface.co/01-ai/Yi-34B/discussions/24)，也说了两种任选一种都可以

**Comment by findmyway** [comment]
哦，那你 load 的是 base model，chat model 只有 safetensors 

https://huggingface.co/01-ai/Yi-34B-Chat/tree/main
