### ISSUE TITLE
fail to start yi-34b-chat tokenizer

### ISSUE THREAD

**Issue by liulfy** [01-ai/Yi#228]
When I try to launch the yi-34b-chat tokenizer, it raises error.
my code is here:
`from transformers import AutoModelForCausalLM, AutoTokenizer
model_path = 'Yi-34B-Chat'
tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)`
The error message is here:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 736, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/tokenization_llama.py", line 166, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] `
How to solve this problem?

**Comment by findmyway** [comment]
Which version of `sentencepiece` are you using?

Consider upgrading to `v0.1.99` if you're using an old version.

**Comment by nick70422** [comment]
I have encountered same problem, mysentencepiece is v0.1.9 too:(

**Comment by findmyway** [comment]
Please make sure your dependencies are compatible with the following constraints.

https://github.com/01-ai/Yi/blob/1f31430b97a8ec49aca63a45e523314f6c31be12/pyproject.toml#L9-L20
