### ISSUE TITLE
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

### ISSUE THREAD

**Issue by dhcn** [01-ai/Yi#302]
You shouldn't move a model when it is dispatched on multiple devices.
Traceback (most recent call last):
  File "/home/yi/workspace/Yi/finetune/sft/main.py", line 416, in <module>
    main()
  File "/home/yi/workspace/Yi/finetune/sft/main.py", line 345, in main
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/opt/conda/envs/yi/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/opt/conda/envs/yi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/opt/conda/envs/yi/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1081, in _configure_distributed_model
    self.module.to(self.device)
  File "/opt/conda/envs/yi/lib/python3.10/site-packages/accelerate/big_modeling.py", line 415, in wrapper
    raise RuntimeError("You can't move a model that has some modules offloaded to cpu or disk.")
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

**Comment by Yimi81** [comment]
Please provide more information such as your environment configuration, sh script and which model you use

**Comment by dhcn** [comment]
> Please provide more information such as your environment configuration, sh script and which model you use

在官方Docker镜像下面，启动的是finetune/scripts/run_sft_Yi_34b.sh
sh里面修改了配置：
export CUDA_VISIBLE_DEVICES=0 #,1,2,3 #limit parallelism to avoid cpu oom

**Comment by Yimi81** [comment]
你启动docker的时候添加--gpus了吗 看报错似乎是没用到gpu

**Comment by dhcn** [comment]
> 你启动docker的时候添加--gpus了吗 看报错似乎是没用到gpu

添加了，从docker里面可以看到nvidia-smi信息

**Comment by Yimi81** [comment]
你可以尝试下6b的正常吗？应该是你的显存不够
