### ISSUE TITLE
Error when trying to run single_inference.py

### ISSUE THREAD

**Issue by Yangfan-96** [01-ai/Yi#357]
### Reminder

- [X] I have searched the Github Discussion and issues and have not found anything similar to this.

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.10
- PyTorch:2.1.2
- CUDA:11.6
- transformers:4.37.1
```

### Current Behavior

Some weights of the model checkpoint at 01-ai/Yi-VL-6B/ were not used when initializing LlavaLlamaForCausalLM: ['model.vision_tower.vision_tower.vision_model.embeddings.class_embedding', 'model.vision_tower.vision_tower.vision_model.embeddings.patch_embedding.weight', 'model.vision_tower.vision_tower.vision_model.embeddings.posit ...]
- This IS expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/data/yangfan/Yi/VL/single_inference.py", line 110, in <module>
    single_infer(args)
  File "/data/yangfan/Yi/VL/single_inference.py", line 62, in single_infer
    output_ids = model.generate(
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/transformers/generation/utils.py", line 1525, in generate
    return self.sample(
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/transformers/generation/utils.py", line 2622, in sample
    outputs = self(
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/yangfan/Yi/VL/llava/model/llava_llama.py", line 87, in forward
    ) = self.prepare_inputs_labels_for_multimodal(
  File "/data/yangfan/Yi/VL/llava/model/llava_arch.py", line 129, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(images)
  File "/data/yangfan/Yi/VL/llava/model/llava_arch.py", line 96, in encode_images
    image_features = self.get_model().get_vision_tower()(images)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/yangfan/Yi/VL/llava/model/clip_encoder/clip_encoder.py", line 53, in forward
    image_forward_outs = self.vision_tower(
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 917, in forward
    return self.vision_model(
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 841, in forward
    hidden_states = self.embeddings(pixel_values)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 182, in forward
    patch_embeds = self.patch_embedding(pixel_values.to(dtype=target_dtype))  # shape = [*, width, grid, grid]
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/yangfan/anaconda3/envs/01ai/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

The models were downloaded from ModelScope。

### Steps to Reproduce

1 from modelscope import snapshot_download
model_dir = snapshot_download('01ai/Yi-VL-6B')
2 move model path.
3 python single_inference.py

**Comment by Yimi81** [comment]
I downloaded the Yi-VL-6B model from **modelscope** through **git clone** and tested it. Everything is normal. Can you download the model by git clone?
![image](https://github.com/01-ai/Yi/assets/66633207/65aa4c42-4ba4-44d3-bba0-e4b19491fea7)

**Comment by Yangfan-96** [comment]
> I downloaded the Yi-VL-6B model from **modelscope** through **git clone** and tested it. Everything is normal. Can you download the model by git clone? ![image](https://private-user-images.githubusercontent.com/66633207/299941878-65aa4c42-4ba4-44d3-bba0-e4b19491fea7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjMzMTAsIm5iZiI6MTcwNjI2MzAxMCwicGF0aCI6Ii82NjYzMzIwNy8yOTk5NDE4NzgtNjVhYTRjNDItNGJhNC00NGQzLWJiYTAtZTRiMTk0OTFmZWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA5NTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Y2NlMDdhOWQ5YTQ1YmI3YzUxMzgxY2ZlMzY0MDhhNGJkNGRhOWZlYzFlMDFiMzhkN2U3ODk1ODZlMjU3OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYJt3lz3GblqNFM8cZyquqZ83bCdGIix3tqHDi8BhPU)


Thank you for your help. I was able to solve the problem by downgrading the Torch version from 2.1.2 to 2.0.1
