### ISSUE TITLE
我使用huggingface导入模型，报错:TypeError: not a string

### ISSUE THREAD

**Issue by ArlanCooper** [01-ai/Yi#63]
Process model_worker - Yi-6B-200K:
Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 63, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 723, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/powerop/.cache/huggingface/modules/transformers_modules/Yi-6B-200K/tokenization_yi.py", line 72, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/powerop/work/rwq/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/serve/model_worker.py", line 213, in __init__
    self.model, self.tokenizer = load_model(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 279, in load_model
    model, tokenizer = adapter.load_model(model_path, kwargs)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/fastchat/model/model_adapter.py", line 70, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 723, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/powerop/.cache/huggingface/modules/transformers_modules/Yi-6B-200K/tokenization_yi.py", line 72, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

请问是哪里问题？

**Comment by ZhaoFancy** [comment]
可以详细描述下你是怎么导入的么？

**Comment by ArlanCooper** [comment]
使用langchain-chatchat，直接配置的模型导入的，
导入的命令具体的不太清楚，请参考https://github.com/chatchat-space/Langchain-Chatchat

**Comment by loofahcus** [comment]
可否提供一下复现代码？看起来像是 load tokenizer.model 这块的时候不太对

**Comment by ArlanCooper** [comment]
这边查看了，用的是fastchat接口，直接读入模型的，
```
python3 -m fastchat.serve.cli --model-path yi-200k
```



我找了找，应该是调用了这些代码读入的 load_model:
```
class BaseModelAdapter:
    """The base and the default model adapter."""

    use_fast_tokenizer = True

    def match(self, model_path: str):
        return True

    def load_model(self, model_path: str, from_pretrained_kwargs: dict):
        revision = from_pretrained_kwargs.get("revision", "main")
        try:
            tokenizer = AutoTokenizer.from_pretrained(
                model_path,
                use_fast=self.use_fast_tokenizer,
                revision=revision,
                trust_remote_code=True,
            )
        except TypeError:
            tokenizer = AutoTokenizer.from_pretrained(
                model_path, use_fast=False, revision=revision, trust_remote_code=True
            )
        try:
            model = AutoModelForCausalLM.from_pretrained(
                model_path,
                low_cpu_mem_usage=True,
                trust_remote_code=True,
                **from_pretrained_kwargs,
            )
        except NameError:
            model = AutoModel.from_pretrained(
                model_path,
                low_cpu_mem_usage=True,
                trust_remote_code=True,
                **from_pretrained_kwargs,
            )
        return model, tokenizer

```

**Comment by loofahcus** [comment]
> fastchat.serve.cli

Sorry, but I cannot reproduce this problem: 
![image](https://github.com/01-ai/Yi/assets/15729967/1711ebff-786b-4955-9018-3553e6e8fcff)

Besides, it's just a base model, chat models will be released in weeks.

**Comment by loofahcus** [comment]
I notice your model path is set to be `yi-200k`, does it mean to be `yi-6b-200k`?

**Comment by ArlanCooper** [comment]
好的，我再试试，谢谢

**Comment by ArlanCooper** [comment]
> I notice your model path is set to be `yi-200k`, does it mean to be `yi-6b-200k`?

这个是我在这里手敲的，真实运行的路径是正确的，感谢您的解答

**Comment by ArlanCooper** [comment]
> > fastchat.serve.cli
> 
> Sorry, but I cannot reproduce this problem: ![image](https://user-images.githubusercontent.com/15729967/281687822-1711ebff-786b-4955-9018-3553e6e8fcff.png)
> 
> Besides, it's just a base model, chat models will be released in weeks.

我这边的运行代码这样，是会报错的:
```
>>> from transformers import (
...     AutoConfig,
...     AutoModel,
...     AutoModelForCausalLM,
...     AutoModelForSeq2SeqLM,
...     AutoTokenizer,
...     LlamaTokenizer,
...     LlamaForCausalLM,
...     T5Tokenizer,
... )
>>> tokenizer = AutoTokenizer.from_pretrained('/data/share/rwq/YI-6B-200K/',trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 686, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 519, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/share/YI-6B-200K/'. Use `repo_type` argument if needed.
>>> tokenizer = AutoTokenizer.from_pretrained('/data/share/rwq/Yi-6B-200K',trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 723, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/powerop/.cache/huggingface/modules/transformers_modules/Yi-6B-200K/tokenization_yi.py", line 72, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/powerop/work/conda/envs/lc_chatglm/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string


```

是因为我的transformer版本问题吗？

**Comment by loofahcus** [comment]
291724ef50f729e45d68f474a7755bbc  tokenizer.model

we use lfs to store tokenizer.model, can you check if this file is already downloaded?

**Comment by ArlanCooper** [comment]
嗯嗯，好的，我找到原因了，我这边模型没有下载完全，谢谢~~~
