### ISSUE TITLE
Missing pypi package in `requirements.txt`

### ISSUE THREAD

**Issue by pranitsh** [01-ai/Yi#78]
Got the below error from running the model through google colab when running `python demo/text_generation.py`
```sh
Namespace(model='01-ai/Yi-6B', tokenizer='', max_tokens=512, streaming=False, prompt='Let me tell you an interesting story about cat Tom and mouse Jerry,', eos_token='<|endoftext|>')
Downloading (…)lve/main/config.json: 100% 717/717 [00:00<00:00, 3.24MB/s]
Downloading (…)/configuration_yi.py: 100% 5.47k/5.47k [00:00<00:00, 22.1MB/s]
A new version of the following files was downloaded from https://huggingface.co/01-ai/Yi-6B:
- configuration_yi.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)/main/modeling_yi.py: 100% 40.6k/40.6k [00:00<00:00, 4.04MB/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/Freshman/Developer/colab/01-ai/Yi/demo/text_generation.py", line 78, in <module>
    main(args)
  File "/content/drive/MyDrive/Freshman/Developer/colab/01-ai/Yi/demo/text_generation.py", line 49, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 552, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`
```

Running `pip install einops` fixes this error and allows the code to run.

If possible, could you add `einops>=0.7` to the `requirements.txt`? Thank you.

**Comment by ShiLuohe** [comment]
I've found the same problem

**Comment by ZhaoFancy** [comment]
The requirements.txt file was removed and we use conda-lock file instead.
